# GitHub Action for generating a contribution graph with a snake eating your contributions
name: Generate Snake

# Grant write permissions to the workflow
permissions:
     contents: write

on:
     schedule:
          # run automatically every 12 hours
          - cron: "0 */12 * * *"

     # allows to manually run the workflow
     workflow_dispatch:

     push:
          branches:
               - main

jobs:
     build:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v3

               - uses: Platane/snk@v3
                 id: snake-gif
                 with:
                      github_user_name: ${{ github.repository_owner }}
                      outputs: |
                           dist/github-contribution-grid-snake.svg?color_snake=hotpink&color_dots=#2d00f7,#6a00f4,#8900f2,#a100f2,#b100e8
                           dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=hotpink&color_dots=#2d00f7,#6a00f4,#8900f2,#a100f2,#b100e8
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

               - name: Push changes
                 uses: crazy-max/ghaction-github-pages@v3.1.0
                 with:
                      target_branch: output
                      build_dir: dist
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}